Styling dashboard images
CodeAnnihilator/CusDeb pull request #26
Opened 2019-02-07 15:03 UTC by temihren

2019-02-07 15:22 UTC, Gerasimov94 requested changes

2019-02-07 15:22 UTC, Gerasimov94 commented on src/assets/images/block-sign.svg
> +<g>
maybe that <g> is unnecessary

2019-02-07 15:22 UTC, Gerasimov94 commented on src/assets/images/check.svg
> +</g>
same

2019-02-07 15:22 UTC, Gerasimov94 commented on src/modules/Dashboard/components/ImagesCardView/ImageCard/Controls/controls.scss
> +	height: 37px;
why you are using a non-multiplied values? Eugene says our multiplier is 4, as i remember.

2019-02-07 15:22 UTC, Gerasimov94 commented on src/modules/Dashboard/components/ImagesCardView/ImageCard/ImageCard.tsx
> +				<FaCircleNotch size={19} fill={COLORS.black} />
? why 19? not 20? or 18? in my oppinion, all sizes must be like X mod 2 === 0

2019-02-08 09:58 UTC, CodeAnnihilator approved these changes

2019-02-08 10:08 UTC, Gerasimov94 approved these changes

2019-02-08 10:11 UTC, merged